### ISSUE TITLE
Implement a switch light-dark mode

### ISSUE THREAD

**Issue by CrazyRacketSmash** [leohuynguyenchi/opensource-project#1]
Implement a switch light-dark button that switches the themes on:
- Main page
- Project page
- Membership page

**Comment by CrazyRacketSmash** [comment]
I plan to put the switch here in main, projects, and memberships pages


![Image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/38270d71-fbba-4ecc-b437-c6891e5bc989)

Any thoughts guys?

**Comment by PipoAT** [comment]
Sorry just now getting to this. I do not mind the location at all, I would though have some indication of what the switch actually means. Like users would not know what that does without trying it

Maybe have some indicator next to it or some symbol that shows light/dark mode or shows that it toggles it?

**Comment by CrazyRacketSmash** [comment]
Yes, that's a good idea. I'll put some text next to it
