### ISSUE TITLE
Year in review: The navigation bar overlays the main section

### ISSUE THREAD

**Issue by CrazyRacketSmash** [leohuynguyenchi/opensource-project#14]
I think the developers don't but the navigation bar there for a reason...because they would overlay the main section but I still think it's best to keep the navigation buttons. What do you yall think?

I'd suggest putting them on the left side right below the Open Source title if you think that's good.

![Image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/393fdb69-e6fd-416e-891f-d77aa568dce4)

**Comment by PipoAT** [comment]
Do we want to match the background color of the navigation bar to be in line with the rest of the website? Like have the design of the nav bar match the behavior of the other pages? Is that the issue here?

**Comment by CrazyRacketSmash** [comment]
Uhhh I just see 1 issue here is that the nav bar just overlay the main contents like in the picture above. I'm not sure if moving the nav bar to the left is ideal...
What do you think?

**Comment by CrazyRacketSmash** [comment]
I think matching the background of the nav bar like other pages is cool. I also think that the "year in review" page is unique so it's best to do the nav bar in a unique way too

**Comment by PipoAT** [comment]
I do not think we need to realign the navigation bar. Matching the background might solve the problem though

**Comment by CrazyRacketSmash** [comment]
I agree. Let's do it that way then

**Comment by PipoAT** [comment]
something like this?

![Image](https://github.com/leohuynguyenchi/opensource-project/assets/93549755/b8dc9968-c6b9-445b-84ea-f5f0f638e9a2)

**Comment by PipoAT** [comment]
Prob be better to get the background across the whole page

**Comment by CrazyRacketSmash** [comment]
Uhhh...Idk about that one lol. Is there anyway to do it the same as the other pages?

**Comment by PipoAT** [comment]
It would be messing with the SCSS for the main.scss file or the year-in-review.scss file

**Comment by CrazyRacketSmash** [comment]
Found it! Just remove the single line:
![image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/d644ba45-2d7f-448b-82c1-355f1c7a5406)

**Comment by PipoAT** [comment]
Nice!
