### ISSUE TITLE
Projects: Filter categories by border colors

### ISSUE THREAD

**Issue by CrazyRacketSmash** [leohuynguyenchi/opensource-project#15]
These projects have different color borders (each color represent each programming language). We can implement a list of categories to filter them when each category is applied.

![Image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/2bc2f170-40f4-4eb9-8858-c4b22eb1ba48)

I'm thinking something like this:

![Image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/c754e522-0e56-4975-9020-69945e6f3898)

Let me know if this is possible

**Comment by PipoAT** [comment]
This is a neat idea! Should we have the filter buttons indicate what programming language is what color? Like hover over the filter color of choice and itll display in a pop up the programming language?

**Comment by CrazyRacketSmash** [comment]
Yessir yessir! I have implemented them like this so far:
![image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/191aba3c-ec3c-481f-a3a6-b512945a9257)
I'll push my changes now so you can see it. Everything is in the projects.html file.
I think it might need an ALL button to show all project cards again if the user want.
Other than that, we'll probably need to adjust the buttons appearance and some sort of styles.

**Comment by CrazyRacketSmash** [comment]
Alright pushed to dev!

**Comment by PipoAT** [comment]
Awesome! Yes I agree we probably need to implement an all button.

At the very least we should have spacing between the buttons and make them rounded edges to match the cards in a way

**Comment by CrazyRacketSmash** [comment]
Yes that would be nice too! Imma dig deep into that
