### ISSUE TITLE
Pull Request Tonight and Tomorrow?

### ISSUE THREAD

**Issue by PipoAT** [leohuynguyenchi/opensource-project#21]
Thinking of doing one pull request tonight with everything we get done through today and then one more tomorrow right before we all agree to submit the final report, etc.

Thoughts?

**Comment by CrazyRacketSmash** [comment]
Yes I agree. I'll get done with the filter and hopefully we can figure out the search bar filter thing today and do a pull request for them?
I'll be free the whole day tomorrow so we can finish this up well!

**Comment by PipoAT** [comment]
That sounds good to me!

**Comment by PipoAT** [comment]
Do a pull request on the actual Twitter/X github to see if it gets accepted?

**Comment by PipoAT** [comment]
@leohuynguyenchi @samwinkelmann

**Comment by CrazyRacketSmash** [comment]
Sure! Let's give it a try
