### ISSUE TITLE
Projects: Improve outlook of each project section

### ISSUE THREAD

**Issue by CrazyRacketSmash** [leohuynguyenchi/opensource-project#4]
In the Projects tab, each project sections are displayed.

Suggestions:
- Insert a color layer/shape behind each section to improve their look

**Comment by PipoAT** [comment]
I will take this and work on it

**Comment by CrazyRacketSmash** [comment]
Sounds good! Let me know if you need some more clarity or brainstorming

**Comment by PipoAT** [comment]
![image](https://github.com/leohuynguyenchi/opensource-project/assets/93549755/c3c78a74-bb70-4a1b-ae9d-2515e99ee69c)


Okay, sounds good! We may need to fix the html or existing css on this as well as for some reason not all the cards on the project page are consistent. 


I added a div tag with the following so that it would produce what I got above

![image](https://github.com/leohuynguyenchi/opensource-project/assets/93549755/3d4cbef1-8811-40fd-842b-a8fd267c3ead)

**Comment by CrazyRacketSmash** [comment]
Wow I see...that's some good progress! Yeah we can dig deep into that. I needa watch some videos for SCSS and hugo stuffs

**Comment by PipoAT** [comment]
scss acts the same way as css

**Comment by PipoAT** [comment]
I see minor differences between the two

**Comment by PipoAT** [comment]
I looked into the inconsistencies in the card layout. It is a result of the length of the descriptions, thus each card's height is dynamically generated and different from one another

**Comment by PipoAT** [comment]
This is an improvement though. Thoughts?

![Image](https://github.com/leohuynguyenchi/opensource-project/assets/93549755/4aab7534-1d2d-4440-97fd-fa867cbbc8a4)

**Comment by CrazyRacketSmash** [comment]
Looks better to me! I don't have any ideas of how to improve it more but we can leave it to "In Review" so we can review it later. Good work man!

**Comment by CrazyRacketSmash** [comment]
I just changed the layout of project cards to look like this:


![Image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/8661de14-99fa-4256-af57-3ca759802ea1)

**Comment by PipoAT** [comment]
That looks so much better. Should we center everything within each card?

**Comment by PipoAT** [comment]
Thoughts? I pushed the text alignment to dev

![Image](https://github.com/leohuynguyenchi/opensource-project/assets/93549755/e4a41425-ee98-4a5c-b3ea-ad769270d2d3)

**Comment by CrazyRacketSmash** [comment]
That looks great! It would be greater if there's a way to center the color border. I guess we can use alignment center for it


![Image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/da6711fe-f80a-4229-802c-110f663d04be)

**Comment by PipoAT** [comment]
That would be ideal. How is the color border attached to the project card?

**Comment by CrazyRacketSmash** [comment]
I'm not sure...Doing some investigation on Chrome dev tools now

**Comment by PipoAT** [comment]
From what I could tell, my suspicion is that it is attached to either the name of the project or is part of some div tag I cant find for some reason

**Comment by CrazyRacketSmash** [comment]
Oh I got it, it's the width property of .border element in SCSS:


![Image](https://github.com/leohuynguyenchi/opensource-project/assets/92219545/7f2c21f8-97d2-4a60-8a59-dd61c04c1784)

**Comment by CrazyRacketSmash** [comment]
Just pushed my changes to dev

**Comment by PipoAT** [comment]
Ohhh perfect! Are we good to close this issue and move to done then?

**Comment by CrazyRacketSmash** [comment]
Yes, we're done with this one!
