### ISSUE TITLE
Update to reflect name change - Twitter to X

### ISSUE THREAD

**Issue by CrazyRacketSmash** [leohuynguyenchi/opensource-project#5]
- On the Twitter web page, change the Twitter icon to X. Same thing for the window tab icon (not sure if this possible).
- On the Twitter web page, any "Twitter" names should be changed to "X".

**Comment by PipoAT** [comment]
Change the mentions of twitter handles so that it is more in line with what is currently existing on twitter/X

**Comment by PipoAT** [comment]
Started on Update to reflect name change - Twitter to X #5


- Started on removing all instances of Twitter and replace with X within the text content of the main, projects, and memberships pages
- Replaced the logo with the X logo in the header of the main, projects, and memberships pages
- Removed instances of @TwitterOSS twitter handle as that is no longer an active twitter/X account
- Changed instances of Twitter to X in the footer of the main, projects, and memberships pages

**Comment by PipoAT** [comment]
Continued on Update to reflect name change - Twitter to X #5

- Replace the twitter logo with the X logo in the Year In Review Page
- Continued to remove instances of @TwitterOSS twitter handle as that is no longer an active twitter/X account
- Replaced the .ico file from the twitter logo to the X logo
