### ISSUE TITLE
Add Navigation Bar to Year in Review Page

### ISSUE THREAD

**Issue by PipoAT** [leohuynguyenchi/opensource-project#6]
@leohuynguyenchi @samwinkelmann 

What do you all think of adding the navigation to the Year In Review Page similar to the rest of the pages?

**Comment by CrazyRacketSmash** [comment]
I think it's a good idea cuz we don't have the link redirect to the main page yet. I can go ahead and create a work item for this

**Comment by PipoAT** [comment]
Pushed to dev the implmentation of the nav bar on the Year in Review Page

**Comment by PipoAT** [comment]
marking as done
