### ISSUE TITLE
Alignment/layout adjustments throughout website

### ISSUE THREAD

**Issue by CrazyRacketSmash** [leohuynguyenchi/opensource-project#7]
Noticed layout issues with the projects page that may need addressed

**Comment by PipoAT** [comment]
Pushed to dev changes to the index/home page in terms of layout
- Removed space not needed from previous functionality that is removed due to it being tied to non-functional twitter/X handles
- Removed dead-links fore careers
- Centered everything

**Comment by PipoAT** [comment]
Pushed to dev changes to the projects and membership pages
- Centered the title/subtitles of both pages

**Comment by CrazyRacketSmash** [comment]
I'm wondering if there are anything else we needa do for this work item guys? If not, I'll just gonna move it to Done

**Comment by samwinkelmann** [comment]
I think it's good, its fairly nondescript but a lot has been done

**Comment by PipoAT** [comment]
Looks good to me. Go ahead and close it.
