### ISSUE TITLE
Projects: Project counts should be updated and associate to search bar

### ISSUE THREAD

**Issue by CrazyRacketSmash** [leohuynguyenchi/opensource-project#9]
When we use the search bar to filter out projects, the project counts should be updated and associated to the searched projects

**Comment by PipoAT** [comment]
The counter is just the JavaScript code within that projects.html file that counts the number of elements with the specific class (or id). That should theoretically take care of itself once the search bar is implemented.

**Comment by PipoAT** [comment]
I can take this on. I deleted a previous comment as I was wrong on how the search bar was implemented

**Comment by PipoAT** [comment]
```<div id="results" class="container hide">Found <span class="count"></span> results for <span class="query"></span></div>```


this line of code already returns the number of search results

**Comment by PipoAT** [comment]
opensource-project\static\js\projects.js

this is the file where we could alter the JS code to make it so that we can always display the count as indicated with the code provided
